import React, { useState } from "react";
import Head from "next/head";
import Navbar from "../components/githubComponents/Navbar";
import axios from "axios";
import Body from "../components/githubComponents/Body";

function github({ data }) {
  const [fetchedRepo, setfetchedRepo] = useState(data);
  const [pageNumber, setpageNumber] = useState(1);
  const [loading, setloading] = useState(false);

  const getRepos = async (num) => {
    setloading(true);

    const res = await axios.get(
      `https://api.github.com/search/repositories?q=created:>2021-08-13&sort=stars&order=desc&page${num}`
    );
    const results = res.data;
    setfetchedRepo(results);

    setloading(false);
  };

  return (
    <div className={"w-screen h-screen flex flex-col"}>
      <Head>
        <title>Github trending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        setpageNumber={setpageNumber}
        getRepos={getRepos}
        pageNumber={pageNumber}
      />

      {loading ? (
        <h3 className="text-lg text-gray-400">loading</h3>
      ) : (
        <Body fetchedRepo={fetchedRepo} />
      )}
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await axios.get(
    "https://api.github.com/search/repositories?q=created:>2021-08-13&sort=stars&order=desc"
  );
  const data = res.data;

  return { props: { data } };
}

export default github;
